import * as Key from "../keys";

export const moonlander = {
  keys: {
    row1: {
      Equal: Key.Equal,
      Digit1: Key.Digit1,
      Digit2: Key.Digit2,
      Digit3: Key.Digit3,
      Digit4: Key.Digit4,
      Digit5: Key.Digit5,
      Digit6: Key.Digit6,
      Digit7: Key.Digit7,
      Digit8: Key.Digit8,
      Digit9: Key.Digit9,
      Digit0: Key.Digit0,
      Minus: Key.Minus,
    },
    row2: {
      Tab: Key.Tab,
      KeyQ: Key.KeyQ,
      KeyW: Key.KeyW,
      KeyE: Key.KeyE,
      KeyR: Key.KeyR,
      KeyT: Key.KeyT,
      Home: Key.Home,
      PageUp: Key.PageUp,
      KeyY: Key.KeyY,
      KeyU: Key.KeyU,
      KeyI: Key.KeyI,
      KeyO: Key.KeyO,
      KeyP: Key.KeyP,
      Backslash: Key.Backslash,
    },
    row3: {
      ControlLeft: Key.ControlLeft,
      KeyA: Key.KeyA,
      KeyS: Key.KeyS,
      KeyD: Key.KeyD,
      KeyF: Key.KeyF,
      KeyG: Key.KeyG,
      End: Key.End,
      PageDown: Key.PageDown,
      KeyH: Key.KeyH,
      KeyJ: Key.KeyJ,
      KeyK: Key.KeyK,
      KeyL: Key.KeyL,
      Semicolon: Key.Semicolon,
      Quote: Key.Quote,
    },
    row4: {
      ShiftLeft: Key.ShiftLeft,
      KeyZ: Key.KeyZ,
      KeyX: Key.KeyX,
      KeyC: Key.KeyC,
      KeyV: Key.KeyV,
      KeyB: Key.KeyB,
      KeyN: Key.KeyN,
      KeyM: Key.KeyM,
      Comma: Key.Comma,
      Period: Key.Period,
      Slash: Key.Slash,
      ShiftRight: Key.ShiftRight,
    },
    row5: {
      ControlLeft: Key.ControlLeft,
      Backquote: Key.Backquote,
      ArrowLeft: Key.ArrowLeft,
      ArrowRight: Key.ArrowRight,
      AltLeft: Key.AltLeft,
      ArrowUp: Key.ArrowUp,
      ArrowDown: Key.ArrowDown,
      BracketLeft: Key.BracketLeft,
      BracketRight: Key.BracketRight,
      ControlRight: Key.ControlRight,
    },
    row6: {
      Backspace: Key.Backspace,
      Escape: Key.Escape,
      Delete: Key.Delete,
    },
    row7: {
      Space: Key.Space,
      Enter: Key.Enter,
      Escape: Key.Escape,
    },
  },
};
