import * as Key from "../keys";

export const ship_map_gmmk_pro = {
  keys: {
    row1: {
      Escape: Key.Escape,
      F1: Key.F1,
      F2: Key.F2,
      F3: Key.F3,
      F4: Key.F4,
      F5: Key.F5,
      F6: Key.F6,
      F7: Key.F7,
      F8: Key.F8,
      F9: Key.F9,
      F10: Key.F10,
      F11: Key.F11,
      F12: Key.F12,
    },
    row2: {
      Backquote: Key.Backquote,
      Digit1: Key.Digit1,
      Digit2: Key.Digit2,
      Digit3: Key.Digit3,
      Digit4: Key.Digit4,
      Digit5: Key.Digit5,
      Digit6: Key.Digit6,
      Digit7: Key.Digit7,
      Digit8: Key.Digit8,
      Digit9: Key.Digit9,
      Digit0: Key.Digit0,
      Minus: Key.Minus,
      Equal: Key.Equal,
      Backspace: Key.Backspace,
      Home: Key.Home,
    },
    row3: {
      Tab: Key.Tab,
      KeyQ: Key.KeyQ,
      KeyW: Key.KeyW,
      KeyE: Key.KeyE,
      KeyR: Key.KeyR,
      KeyT: Key.KeyT,
      KeyY: Key.KeyY,
      KeyU: Key.KeyU,
      KeyI: Key.KeyI,
      KeyO: Key.KeyO,
      KeyP: Key.KeyP,
      BracketLeft: Key.BracketLeft,
      BracketRight: Key.BracketRight,
      Backslash: Key.Backslash,
      PageUp: Key.PageUp,
    },
    row4: {
      ControlLeft: Key.ControlLeft,
      KeyA: Key.KeyA,
      KeyS: Key.KeyS,
      KeyD: Key.KeyD,
      KeyF: Key.KeyF,
      KeyG: Key.KeyG,
      KeyH: Key.KeyH,
      KeyJ: Key.KeyJ,
      KeyK: Key.KeyK,
      KeyL: Key.KeyL,
      Semicolon: Key.Semicolon,
      Quote: Key.Quote,
      Enter: Key.Enter,
      PageDown: Key.PageDown,
    },
    row5: {
      ShiftLeft: Key.ShiftLeft,
      KeyZ: Key.KeyZ,
      KeyX: Key.KeyX,
      KeyC: Key.KeyC,
      KeyV: Key.KeyV,
      KeyB: Key.KeyB,
      KeyN: Key.KeyN,
      KeyM: Key.KeyM,
      Comma: Key.Comma,
      Period: Key.Period,
      Slash: Key.Slash,
      ShiftRight: Key.ShiftRight,
      ArrowUp: Key.ArrowUp,
      End: Key.End,
    },
    row6: {
      CapsLock: Key.CapsLock,
      AltLeft: Key.AltLeft,
      Space: Key.Space,
      MetaRight: Key.MetaRight,
      ControlRight: Key.ControlRight,
      ArrowLeft: Key.ArrowLeft,
      ArrowDown: Key.ArrowDown,
      ArrowRight: Key.ArrowRight,
    },
  },
};
